### ISSUE TITLE
Auth support?

### ISSUE THREAD

**Issue by mckernanin** [GingkathFox/esiJS#6]
Is there a way to make authenticated requests?

**Comment by 0xf0xx0** [comment]
There is, i just dont know how to implement it. If you know how, feel free to open a PR!

**Comment by joemanfoo** [comment]
@GingkathFox - I think what @mckernanin is looking for is that the requests fired off to ESI include the correct header `Authorization: Bearer <access token>`.

Speaking of headers, I think it should be something that the requests return (configurable to do so at least), so include the `headers` and `body` since: https://docs.esi.evetech.net/docs/warning_header.html

I'm thinking that perhaps the `esi.json` file be setup and renamed to something more akin to a `config.js` where:
`esi.json`
```
{
  "link": "https://esi.evetech.net/latest/",
  "dataSource": "tranquility"
}
```

becomes:
`config.js`
```
const config = {
  esi: {
    link: process.env['ESI_LINK'] || 'https://esi.evetech.net/latest/',
    dataSource: process.env['ESI_DATASOURCE'] || 'tranquility',
    warnings: process.env['SHOW_ESI_WARNINGS'] || false,
    esiId: process.env['ESI_CLIENT'] || null,
    esiSecret: process.env['ESI_SECRET'] || null,
    redirectUrl: process.env['ESI_AUTH_REDIRECT_URL'] || null,
  }
};
export default config;
```

This way folks can configure which ESI version they are coding against and with the `config.esi.warnings` if set to `true` then return ESI response headers (easiest option) or setup logging (could be much more difficult) so developers know they need to plan code updates for the upcoming changes. I suppose the above code makes the assumption that the implementation method is on a nodejs server and not on client, but if on client then someone wouldn't place the `esiId`, `esiSecret`, etc on client.

**Comment by 0xf0xx0** [comment]
> I think what @mckernanin is looking for is that the requests fired off to ESI include the correct header `Authorization: Bearer <access token>`.

Hmm, you might be right. ill see what i can do.

**Comment by 0xf0xx0** [comment]
@joemanfoo quick question: would you rather the requests return something like this:

```json
{
    headers,
    data
}
```
?

**Comment by ghost** [comment]
I'd also be interested in this, however you decide to implement it. It would open up all those auth-only endpoints for information, such as player details, solar system owners, etc.

**Comment by 0xf0xx0** [comment]
Alrighty. I have no way to test that seeing as ive never bought anything off of the store, I'll see what i can do.

**Comment by 0xf0xx0** [comment]
Warning added in v3.0.4, will officially switch to returning headers also in v4.0.0. Thanks!

**Comment by ghost** [comment]
Just to give my two cents, it might be useful to "assume" the user using this API already has a way of authenticating. That you only need the token to be passed and you can add it to the parameter. While I wait for 4.0.0 to be released, I went ahead and got the following created for my personal code's purpose of showing a player's skill queue. Thought it might be useful to help you figure out how you want to tackle player auth:

```
Axios.get(`https://esi.evetech.net/latest/characters/${charId}/skillqueue?token=${token}`)
```

**Comment by 0xf0xx0** [comment]
sure, ill add a `token` field into the config and include it in calls.

**Comment by 0xf0xx0** [comment]
@K73SK Token field added, and ~~i think~~ all authenicated endpoints in character and corporation on the dev branch. Wanna try it out and see if i missed anything?

**Comment by ghost** [comment]
@GingkathFox Sorry for no response right away. I was actually able to modify my Discord Bot to where I could handle all the API stuff within my app without pulling in 3rd party dependencies (this one in particular). Reason was only to get the skills under my belt so I could better understand how I was doing everything and how all that fun stuff worked. So with that, I won't be able to test this against my application anymore, but hopefully @mckernanin could provide feedback on whether it works for him or not? Or if you want to point me to a specific commit to see if it looks similar/same as what I'm doing for authentication, I can let you know visually :D

**Comment by 0xf0xx0** [comment]
glad you could work it out in your bot! The commit for character and corps is here: 6832a764b74027f3654b76eaedbe95405a4f171f

**Comment by ghost** [comment]
As far as I can tell, it should work. Ofc, haven't tested it (hoping Mckernanin or @joemanfool  can respond haha). 

Only feedback I have is a misspelling:
```
throw throwError(`You used a authenicated function without a token. ....
```
(authenticated, not authenicated). I know, not much feedback xD But just looking over it, my brain says it should work. But being a programmer as well, there's probably a 95% chance that's wrong since computers like to prove us wrong :)

**Comment by 0xf0xx0** [comment]
> there's probably a 99.9% chance that's wrong

ftfy xD

and thats how you spell it? huh. Thanks :3

**Comment by 0xf0xx0** [comment]
@mckernanin @joemanfoo All authed endpoints have been added, install with `npm i esijs@dev` and tell me how it works :D
